### ISSUE TITLE
How to use with Webone?

### ISSUE THREAD

**Issue by BjornB2** [smallsco/macstodon#9]
Hi!

I have WebOne running on my network. I can use it as a proxy in Netscape, but how do I use it with Macstodon? When I start Macstodon I see no option to configure anything before entering the server address. I am using MacTCP (still waiting for more memory to arrive so I can install OpenTransport). I don't think I can set a system wide proxy? 

Thanks

**Comment by smallsco** [comment]
Hello!

You can set a system-wide proxy using the Internet Config application. Download it from here: https://macintoshgarden.org/apps/internet-config-202

Select the "Firewalls" button, then place a checkbox next to "Use HTTP Proxy" and fill in the IP and port of your WebOne server. Then save and quit the app, and relaunch Macstodon - it will automatically pick up the proxy settings you saved.

<img width="456" alt="image" src="https://github.com/smallsco/macstodon/assets/1906551/0bab82eb-7133-4857-b0cc-e40771092ed9">

**Comment by BjornB2** [comment]
Thanks for your very helpful answer! Going to try it right away :D

**Comment by BjornB2** [comment]
Installed it but it doesn't seem to do anything. I tried Macweb and Netscape but both don't open pages that redirect to https. When I set the proxy in Netscape itself it works. 
I guess I have some figuring out to do. I also might need to wait for my memory upgrade since my 4MB RAM might be a bit short for Macstodon.

**Comment by smallsco** [comment]
MacWeb is a very old web browser and doesn't support Internet Config.

For Netscape I'm not sure if it recognizes Internet Config or not. Later versions might, or it might not since Netscape has built-in support for proxies anyway.

Macstodon will read the proxy configuration that you have saved in Internet Config. When you enter your instance name, you need to use "http" instead of "https", this is very important as WebOne will perform transparant redirection (and MacPython doesn't support https anyway). 

In your WebOne configuration, also try adding your instance's domain to the ForceHTTPS section of the config file, and update the user agent - some instances require this (see the "Known Issues" section of the Macstodon readme).

4 MB is short when it comes to loading images, but if you disable images and only load a few toots at a time you might be able to get away with it.

**Comment by BjornB2** [comment]
Thanks again! I'm kinda new to this vintage Mac stuff so I've got a lot to learn. 
For now when I launch Macstodon I can enter the server url but then the 'connecting' screen shows shortly and then becomes blank. I think I better wait until the RAM upgrade arrives :)
![IMG_1553 groot](https://github.com/smallsco/macstodon/assets/3328086/eb94966c-2a59-4d12-9603-024359e60429)

**Comment by smallsco** [comment]
Hm... I think that's the "Out of Memory" dialog but you have so little free RAM that it can't even draw the dialog properly and just hangs 😔

**Comment by BjornB2** [comment]
Yeah could be that indeed. Well I've got a full upgrade to 10mb on the way so I'll try again after I've installed that. Thanks for your help and patience.

**Comment by BjornB2** [comment]
Just installed Macstodon on my Dutch system 7.1 Macintosh Performa 200 (AKA Classic II). The strange thing is that all finder menu items suddenly are English after installing. I also get a message that the system extension "Network Extension" is too old. 

![IMG_1603](https://github.com/smallsco/macstodon/assets/3328086/951ab0dc-a0e1-40d6-a154-bb760e654e63)

![IMG_1604](https://github.com/smallsco/macstodon/assets/3328086/b4b04cfc-be4d-4e19-ab30-740784c3c0b4)

![IMG_1605](https://github.com/smallsco/macstodon/assets/3328086/ed6f8262-31e8-4edd-a70c-47c93ef8011d)

It does work in the end though 😊 
But I'll go back to a backup of my diskimage before installing Macstodon since it somehow messes up the language of my system.

**Comment by smallsco** [comment]
Argh, I didn't test at all with international OS versions because I don't have any. So the installer is overwriting your localized system components... 😅

No idea how to fix this, I guess I could just install the app on international OS versions and say it's up to you to find the appropriate localized versions of the extensions yourself.

There should have been a "Macstodon Installer Log" created that shows you what was installed, but I can also write it here:
 - Finder 7.1.3, Finder Help 7.1.3, Network Extension 7.1.3, Finder Scripting Extension 7.1.3 (if you're running an earlier system than 7.5 with a Finder older than 7.1.3 on a 68K machine)
 - CFM-68K Runtime Enabler, ObjectSupportLib, NuDragLib.slb (if you're running an earlier system than 7.6 on a 68K machine)
 - AppleScript 1.1 and Scripting Additions (if you're on a 68K machine without AppleScript already installed)
 - PlainTalk Speech Manager 1.5 (if you don't have it already installed)

So it sounds like your Finder was overwritten, but you have both the English and localized version of Network Extension (and your localized version is now too old to work with the new Finder).

I'm very sorry that this happened and will try to come up with a work around for the next release.

**Comment by BjornB2** [comment]
I made a backup of my harddrive image so no harm done here 😊
Would be nice if you can find a solution. If I can assist in any way just let me know!

**Comment by smallsco** [comment]
This is a very busy month for me IRL so it will be a while before I can implement a proper work-around. In the mean time I will zip up an app-only version without the installer and stick it here.

**Comment by BjornB2** [comment]
No rush. The computer is over 30 years old. It can wait a bit longer haha

**Comment by smallsco** [comment]
You can download a standalone copy now from here: https://github.com/smallsco/macstodon/releases/download/v1.2/Macstodon1.2.sit.hqx

The CFM-68K extensions are mandatory and required for Macstodon to function at all, I have included them with this download. However in order to get text to speech working you will need to manually locate and install Finder 7.1.3, AppleScript 1.1, and PlainTalk 1.5 that are appropriately localized for your OS.

**Comment by BjornB2** [comment]
Oh great I will try tomorrow! I don't really care for the speech thing btw.

Thanks!

**Comment by smallsco** [comment]
I've just published a Macstodon 1.2.1 release with an updated installer, that won't overwrite the Finder on international/localized copies of System 7.1.

Closing this issue.
